env:
  - EMACS=emacs23
  - EMACS=emacs24
before_install:
  # PPA for stable Emacs packages
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox
script:
  - emacs --version
  - autoreconf -i
  - ./configure
  - make distcheck
